### ISSUE TITLE
Could not find path to the mlint executable in the configuration file.

### ISSUE THREAD

**Issue by htyeim** [Gimly/vscode-matlab#1]
thank you for the extension.
i have install it but when open a m file it alway say :
Could not find path to the mlint executable in the configuration file.
is it normal?

**Comment by Gimly** [comment]
Hi there, wouhou, you're the first issue :smile:.

Anyway, yes it's normal. It's because you haven't setup the path to the mlint which is used to get errors and warnings on the code directly inside VS Code.

It's explained at the end of the [Readme](https://github.com/Gimly/vscode-matlab#setting-up-linter)

For simplicity, I'm copying it here:

* Open the *User Settings* by going to *File*>*Preferences*>*User Settings*
* On the right pane, where you have the *settings.json* file open, add to the json file.

	`"matlab.mlintpath" : "path to your mlint.exe file"` 

	For example : 
	
	`"matlab.mlintpath": "C:\\Program Files (x86)\\MATLAB\\R2012a\\bin\\win32\\mlint.exe"`
* Save your *settings.json* file
* Now, when you open a Matlab document (*.m*), VS Code displays warnings and errors. 
  
  **Remark:** If you don't want the *lint on save* option and you want to remove the error message being displayed when the extension activates, change the `matlab.lintOnSave` option in the settings file to `False`.

**Comment by htyeim** [comment]
:+1: 
thank you!
and the vscode-fortran is also very useful, when i look some  FORTRAN code writed long long long time ago.....

**Comment by Gimly** [comment]
You're welcome, happy to be able to help :smile:.

**Comment by NazarioJL** [comment]
I have this entry --> "matlab.mlintpath": "C:\\Program Files\\MATLAB\\R2016b\bin\\win64\\mlint.exe" in my settings.json file but I still get the message : "Could not find path to the mlint executable in the configuration file."

**Comment by amauragis** [comment]
@NazarioJL You need to escape the backslashes.  Replace your entry with:
 ` "matlab.mlintpath": "C:\\Program Files\\MATLAB\\R2016b\\bin\\win64\\mlint.exe"`

**Comment by NazarioJL** [comment]
@amauragis I was escaping, but I missed the single backslash behind the bin, so I had 
`"matlab.mlintpath": "C:\\Program Files\\MATLAB\\R2016b\bin\\win64\\mlint.exe"
`instead of 
`"matlab.mlintpath": "C:\\Program Files\\MATLAB\\R2016b\\bin\\win64\\mlint.exe"`

Thank you so much! Awesome extension.

**Comment by Gimly** [comment]
@NazarioJL glad you found the solution. It's kind of annoying to have to escape the backslashes, I concurr.

**Comment by redzt** [comment]
Hi, I am using Matlab on Mac, where can I find the Mac version of "mlint.exe"

**Comment by redzt** [comment]
found solution on another issue. Thank you for your extension 👍 :-) @Gimly

**Comment by bill52547** [comment]
@redzt Hi, where did you find the alternate of mlint.exe on Matlab-MAC? I am facing the same issue. Thank you!

**Comment by redzt** [comment]
Hi, according to issue#4 of this repo, the path is something like this `/Applications/MATLAB_RXXXx.app/bin/matlab`. You can use `locate` command to find what you want. @bill52547

**Comment by Gimly** [comment]
@bill52547 Hi, in the README of the repository as well as on the extension's home page, you have another example:
```
"matlab.mlintpath": "/Applications/MATLAB_R2016a.app/bin/maci64/mlint"
```

As @redzt suggested, either [use the locate](http://osxdaily.com/2011/11/02/enable-and-use-the-locate-command-in-the-mac-os-x-terminal/) command and search for "mlint", or check for the matlab folder under `/Applications` and try to find `mlint` in a folder under `bin`.

**Comment by bill52547** [comment]
@Gimly @redzt 
Thank you both!!
I found the mlint file from Gimly's suggestion.

**Comment by plus7wist** [comment]
If you do not have any `mlint` installed and you do not want to use it at all, you can write `"matlab.lintOnSave": false` into your setting file. That warnning will be suppressed.

**Comment by Foadsf** [comment]
I wish Open Source replicas of MATLAB, (Octave, Scilab, FreeMat) would come up with a mlint replacement.

**Comment by rsylvan** [comment]
@Foadsf I was able to get around this by installing a trial version of MATLAB and then manually pointing to "/Applications/MATLAB_R2019b.app/bin/maci64/mlint"

I don't think using (at least this) command line tool requires a license

**Comment by matrix137** [comment]
Hello!
Is there a way to include several paths for the Matlab mlint?
In my case, I was always switching between different servers and the mlint paths are different on different servers.
