### ISSUE TITLE
Incorrect highlighting of inline syntax of conditional statement

### ISSUE THREAD

**Issue by vr050714** [Gimly/vscode-matlab#101]
There is incorrect colors of keywords after comma operator in case of a single line statement.
![bad-inline-syntax-colors](https://user-images.githubusercontent.com/8076819/70154557-baff1580-16c1-11ea-8e77-6e47a6ed5bff.PNG)

**Comment by rlivings39** [comment]
Created https://github.com/mathworks/MATLAB-Language-grammar/issues/19
