### ISSUE TITLE
Incorrect highlighting of comments inside events block of class definition

### ISSUE THREAD

**Issue by vr050714** [Gimly/vscode-matlab#102]
The comment inside events block has wrong color
![bad-comment-highlighting-events-block](https://user-images.githubusercontent.com/8076819/70155422-475e0800-16c3-11ea-9b6b-88544ea35f11.PNG)

**Comment by rlivings39** [comment]
Created https://github.com/mathworks/MATLAB-Language-grammar/issues/20
