### ISSUE TITLE
Incorrect keyword highlighting when comma operator is used in IF statement

### ISSUE THREAD

**Issue by vr050714** [Gimly/vscode-matlab#103]
Incorrect highlighting of single line IF statement has impact on surrounding code colors.
![bad-case-highlighting](https://user-images.githubusercontent.com/8076819/70157046-eab01c80-16c5-11ea-90d4-eea2d577fb73.PNG)
Probably, the issue is similar to #101

**Comment by rlivings39** [comment]
Created https://github.com/mathworks/MATLAB-Language-grammar/issues/19
