### ISSUE TITLE
mlint not working under Linux

### ISSUE THREAD

**Issue by oerpli** [Gimly/vscode-matlab#11]
I specified the mlint path and saved some files where the mlint suggests some changes but those things did not show up in VS Code:

Running mlint in the terminal resulted in:
```

./mlint /test.m 
L 6 (C 3): Parse error at '=': usage might be invalid MATLAB syntax.
L 10 (C 6): Terminate statement with semicolon to suppress output (within a script).
L 11 (C 5): Terminate statement with semicolon to suppress output (within a script).
L 15 (C 5): Terminate statement with semicolon to suppress output (within a script).
L 21 (C 9): Terminate statement with semicolon to suppress output (within a script).
L 23 (C 1-3): Terminate statement with semicolon to suppress output (within a script).
L 24 (C 1-3): Terminate statement with semicolon to suppress output (within a script).
L 25 (C 1): Terminate statement with semicolon to suppress output (within a script).
L 26 (C 1-2): The value assigned to variable 'Ax' might be unused.
L 26 (C 4): Terminate statement with semicolon to suppress output (within a script).
L 28 (C 48-49): Possible inappropriate use of == operator. Use = if assignment is intended.
L 28 (C 48-49): Terminate statement with semicolon to suppress output (within a script).
```

Is the format maybe different for linux? I'm using R2015b.

**Comment by oerpli** [comment]
The regex should be fine though - I just tested it here:
http://regexr.com/3fckq

**Comment by Gimly** [comment]
Mmh, that's really strange. The output should indeed be working. I'll have to test that, but that means I'll have to install a VM with Linux and Matlab on it. What Linux distribution did you try that on?

If you have time, you could easily clone the repo, put a breakpoint in the code where the parsing of the mlint is done and check the output of the reading of the console. I'm wondering if it could be an issue with the encoding.

**Comment by subhammridha** [comment]
It works fine with me though. I'm using matlab 2016b in centos 7.3

**Comment by Gimly** [comment]
Any news about this? Otherwise I will close the issue. Thanks

**Comment by oerpli** [comment]
Sorry for not getting back to you earlier. Had a lot of things going on and then finished my matlab related project.
I checked in yesterday if the problem still exists, which was the case.
Though I noticed that I was using Linux Mint 15 and had a few other problems with encoding in other command line related tools. If I happen to use it again on an up to date OS I will investigate.

**Comment by Gimly** [comment]
Ok, thanks for the update 🙂. I'm leaving the issue closed for new as it's not clear whether it's an issue related to your system or to the extension.

If you can investigate further and are see that it's coming from the extension feel free to reopen the issue or create a new one, giving the info you could find.

Thanks for your help.
