### ISSUE TITLE
Variables colored as functions (blue)

### ISSUE THREAD

**Issue by Galileji** [Gimly/vscode-matlab#111]
When I name variables with names that are also names of functions they get colored as such.
For example `gamma` or `beta` or even `i` and `j` are colored in blue, whereas I am using them as variables.

I understand that probably it is impossible for the extension to recognize when you are using something as a variable or as a function, but a workaround could be to allow the user to decide some exceptions so that, say, all greek letters and single roman letters are never recognized as functions.
Then the user could decide by themselves, depending on their coding style.

**Comment by Galileji** [comment]
I found a solution. You can go to your  c:\users\username\.vscode\extensions\gimly81.matlab-1.6.0\syntaxes, and edit matlab-functions.tmLanguage by removing the names you don't want to show up as functions.
Sorry if this was obvious for somebody else, but for me it was not :)

**Comment by rlivings39** [comment]
I'd say it's non-obvious. The syntax highlighting is pretty static so on the implementation side it's hard to dynamically skip things when they're used as variables. At least as far as I'm aware.

**Comment by Galileji** [comment]
Yes I can Imagine that, I just meant the solution I proposed could be obvious for someone who is familar with textmate files... but I'm not, unfortuantely!
