### ISSUE TITLE
New `.?` operator not recognized as valid syntax

### ISSUE THREAD

**Issue by Dev-iL** [Gimly/vscode-matlab#112]
This relates to the new argument validation functionality introduced in R2019b. 

Consider the following quote from the [MATLAB docs](https://www.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html#mw_de9b2056-9dc2-421c-9c7e-d2c4400a95be):

> **Name-Value Arguments from Class Properties**
>A useful function syntax in MATLAB uses the public properties of a class for the names of name-value arguments. To specify name-value arguments for all settable properties defined by a class (that is, all properties with public `SetAccess`), use this syntax in an `arguments` block:
>
>     structName.?ClassName

However, as of v2.0.0 this is not recognized as valid syntax:

![image](https://user-images.githubusercontent.com/6509619/80908228-efd1d000-8d26-11ea-82bf-ff0535090b13.png)

**Comment by rlivings39** [comment]
The error you're seeing is coming from the MATLAB MLINT executable which is run from your local MATLAB install. What version of MATLAB do you have installed? Check the setting `matlab.mlintpath` to see if you've customized the path to point to an older MATLAB.

**Comment by Dev-iL** [comment]
Thanks for the solution @rlivings39! 

I have 2 versions installed: R2018a and R2020a. After changing the config as you suggested (from 2018a to 2020a) and restarting VBCode, this indeed stopped being marked as an error.
