### ISSUE TITLE
Suggestion: Comment headline highlights

### ISSUE THREAD

**Issue by timfelle** [Gimly/vscode-matlab#116]
Is it possible to update the Colorization such that Headline comments (`%%`) Will get a brighter color than the regular comments. I know the extension "Better Comments" provide such functionality for other commenting commands, such as alerts (`% ! `) so i think it should be possible here as well.

**Comment by rlivings39** [comment]
We could likely do something here. Created https://github.com/mathworks/MATLAB-Language-grammar/issues/35 in the grammar repo to take a look.
