### ISSUE TITLE
try; catch; end one liner support missing

### ISSUE THREAD

**Issue by SiFreZi** [Gimly/vscode-matlab#124]
Hi,
I like this extenstion very much. Regrettably the extension does not support try; catch; end one liner statements.
The 'end' is not recognized as keyword and the indentation is buggy.
I'd love to see an update here.
Best regards,
Simon

**Comment by rlivings39** [comment]
Can you paste the code here that has the issues? The syntax highlighting is handled by https://github.com/mathworks/MATLAB-Language-grammar so we should open that as an issue there.

**Comment by SiFreZi** [comment]
Sample code
`try something; catch e; end`
The indent issue is related to AffenWiesels matlab-formatter 😅

**Comment by rlivings39** [comment]
Opened an issue for the highlighting repo
