### ISSUE TITLE
Interpolated string semicolon

### ISSUE THREAD

**Issue by SNDST00M** [Gimly/vscode-matlab#128]
Semicolons next to interpolated string is somehow part of the string. Should be a separate symbol token?

**Comment by rlivings39** [comment]
Can you post a code snippet and screenshot showing the problem?

**Comment by 4086606** [comment]
```
close all;
```

`all;` has token `matlab.string.interpolated`. Seems like upstream issue in MATLAB textmate bundle.

**Comment by 4086606** [comment]
Ah you opened an issue for it before COVID..

https://github.com/mathworks/MATLAB-Language-grammar/issues/7
