### ISSUE TITLE
Highlight error in code

### ISSUE THREAD

**Issue by OzelotVanilla** [Gimly/vscode-matlab#131]
![image](https://user-images.githubusercontent.com/59910575/122321261-2a5ff180-cf56-11eb-85af-f8db925d94bc.png)

It seems that the highlighter does not work properly. The variable `target`, `input` function, and semicolons, are in a wrong colour.

Also, the equal sign does not highlight as a operator.

**Comment by 4086606** [comment]
Could you please give the code sample? I have a repo with MANY Matlab syntax fixes ready to go

**Comment by OzelotVanilla** [comment]
At now, the highlight goes like this

![image](https://user-images.githubusercontent.com/59910575/122706318-43381200-d28a-11eb-9830-f41f71bb0f50.png)

I will paste code in next block.

**Comment by OzelotVanilla** [comment]
function sln = ahp()
    % First clear the window
    clc;


    % Ask user to input the target (highest layer)
    target = input("Please input your final target: ", "s");
    fprintf("\n");


    % Ask user to input criterion
    disp("Enter your criterion one by one. After entering all criterion, press enter.");
    layers       =  [""];    % Criterion of evaluation. Init with empty string to avoid bug
    solutions    =  [""];    % Solutions of target
    input_count  =  1;       % Number in propmt
    ri           =  [0, 0, 0.58, 0.90, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49, 1.51, 1.53];

    % Get layers
    while true
        % Add criterion to layers
        while true
            s = input("Enter your criteria [" + input_count + "]: ", "s");
            if s ~= ""
                layers = [layers, s];
                input_count = input_count + 1;
                if input_count > length(ri)
                    disp("[ WARN ]  Reach the limit of layers.");
                    break;
                end
            else
                break;
            end
        end

        % If there is only one criteria, make warnings
        len = length(layers);
        if length(layers) <= 2
            fprintf("\n");

            if len <= 2
                disp("[!ERROR]  You must add at least two layer.")
            end

            if input("Enter ""y"" if you want to add more layers: ", "s") == "y"
                disp("[ INFO ]  Re-creating start");
                fprintf("\n");
                continue;
            else
                disp("[!ERROR]  This program refuse to run any more...");
                fprintf("\n");
                return;
            end
        end
        clear len;

        % Break after creating
        break;
    end
    layers = layers(2 : end)    % Get the layers to compare
    input_count = 1;

    % Get solutions
    while true
        % Add solutions to solutions
        while true
            s = input("Enter your solution [" + input_count + "]: ", "s");
            if s ~= ""
                solutions = [solutions, s];
                input_count = input_count + 1;
                if input_count > length(ri)
                    disp("[ WARN ]  Reach the limit of solutions.");
                    break;
                end
            else
                break;
            end
        end

        % If there is only one criteria, make warnings
        len = length(solutions);
        if length(solutions) <= 2    % It has a empty string in the first place
            fprintf("\n");

            if len <= 2
                disp("[!ERROR]  You must add at least two solutions.")
            end

            if input("Enter ""y"" if you want to add more solutions: ", "s") == "y"
                disp("[ INFO ]  Re-creating start");
                fprintf("\n");
                continue;
            else
                disp("[!ERROR]  This program refuse to run any more...");
                fprintf("\n");
                return;
            end
        end
        clear len;

        % Break after creating
        break;
    end
    solutions = solutions(2 : end)    % Get the solution (drop first empty string)
    clear input_count;


    % Make the matrix de comparison

    % Ask if there are different people doing the evaluation
    fprintf("\n");
    if input("Are there two or more people doing the evaluation (enter ""y"" if so) ?  ", "s") == "y"
        num_of_people  =  input("How many people?  ");
        people_id      =  1;
        cmp            =  cell(1, num_of_people);
        while people_id <= num_of_people
            cmp_n = getCmp(layers, num_of_people, people_id);
            if isempty(cmp_n)
                return;
            end
            cmp{people_id} = cmp_n;
            people_id = people_id + 1;
        end

        % Transfer it into one matrix using geomatric average
        len         =  length(layers);
        len_cmp     =  length(cmp);
        transferred =  diag(ones(1, len));
        for n = 1 : len
            for m = (n + 1) : len
                prod_each = 1;
                for q = 1 : len_cmp
                    prod_each = prod_each * cmp{q}(n, m);
                end
                transferred(n, m) = power(prod_each, 1 / len_cmp);
            end
        end
        
        for n = 1 : len
            for m = 1 : n
                prod_each = 1;
                for q = 1 : len_cmp
                    prod_each = prod_each * cmp{q}(n, m);
                end
                transferred(n, m) = power(prod_each, 1 / len_cmp);
            end
        end
        cmp = transferred;
    else
        cmp = getCmp(layers, 1, 1);
        if isempty(cmp)
            return;
        end
    end

    fprintf("\n");
    cmp
    [v, d]   =  eig(cmp);
    v        =  abs(v(:,1));
    cmp_wgt  =  v / (sum(v(:,1)));
    clear v d;


    % Get the review of each solution
    reviews  =  {};    % The "cell" ( {} ) can contain matrix one by one, but not concat them

    % Ask user if they are doing traditional AHP, and get final score of solutions
    if input("Will you use traditional AHP to evaluate each solution (enter ""y"" if so)?  ", "s") == "y"
        % TODO: No code here
    else
        reviews  =  getScore(layers, solutions);
        len_s    =  length(solutions);
        len_y    =  length(layers);
        sln_evl  =  zeros(1, len_s);
        for n = 1 : len_s
            for m = 1 : len_y
                sln_evl(n) = sln_evl(n) + cmp_wgt(m) * reviews(n, m);
            end
        end
        reviews
        clear reviews len_s len_y;
        sln = [""];
        [x, y] = find(sln_evl == max(sln_evl));
        for n = 1 : length(y)
            sln = [sln, solutions(n)];
        end
        sln = sln(2 : end);
        if length(sln) > 1
            disp("Best solutions for """ + target + """ are: ");
        else
            disp("Best solutions for """ + target + """ is: ");
        end
        sln
        return;
    end
end

function cmp = getCmp(layers, num_of_people, people_id)
    ri     =  [0, 0, 0.58, 0.90, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49, 1.51, 1.53];
    cmp    =  [];
    len_l  =  length(layers);

    % Main loop of making comparison matrix, if it is OK, end while
    while true
        fprintf("\n");
        cmp = diag(ones(1, len_l));    % Init a matrix with 1 in diag
        disp("According to the table below, enter your evaluation of two criteria.");
        disp("You can also enter minus number for fraction.");
        disp("For example, if you think criteria """ + layers(1) + """ is a little important than """ + layers(2) + """, " + "enter 3");

        % Print scale table
        Scale        =  [1; 3; 5; 7; 9; "Mid value"; "1/n"];
        Meaning      =  ["Same priority"; "A little important"; "Distinctly important"; "Strongly important"; "Extremely important"; ...
                         "Between two levels"; "The second item is dominant"];
        scale_table  =  table(Scale, Meaning)
        clear scale_table Scale Meaning;

        % Enter scales to matrix
        for n = 1 : len_l
            for m = (n + 1) : len_l
                while true
                    if num_of_people > 1
                        e = input("People [" + people_id + "] compare """ + layers(n) + """ to """ + layers(m) + """: ");
                    else
                        e = input("Compare """ + layers(n) + """ to """ + layers(m) + """: ");
                    end
                    if isempty(e)
                        disp("[ WARN ]  No input will be seen as ""1"".");
                        e = 1;
                    elseif 0 < e && e <= 9
                        e = e;
                    elseif -9 <= e && e < 0
                        e = 1 / (-e);
                    else
                        disp("[!ERROR]  Wrong number. Input again.");
                        continue;
                    end
                    cmp(n, m) = e;
                    break;
                end
            end
        end

        % Create the lower left corner of the matrix
        for n = 1 : length(cmp)
            for m = (n + 1) : length(cmp)
                cmp(m, n) = 1 / cmp(n, m);
            end
        end

        % Check the validity of this matrix

        % Get the max eigenvalue of cmp
        len  =  length(cmp);
        % If CI/RI < 0.15
        fprintf("\n");
        cr = ((max(eig(cmp)) - len) / (len - 1)) / ri(len);
        if cr < 0.15
            disp("[ INFO ]  The value you have inputted passed the check.")
        else
            disp("[ INFO ]  The value you have inputted is invalid. Please re-input your evaluation of criterion.");
            disp("[ INFO ]  Your cr: " + cr);
            if input("Exit this program (input ""y"" to exit) ?  ", "s") == "y"
                cmp = [];
                return;
            end
            if input("Force use this result (enter ""y"" if you want) ?  ", "s") == "y"
                disp("[ WARN ]  Bad value accepted.");
            else
                disp("[ INFO ]  Re-creating start");
                continue;
            end
        end

        clear len ri;
        break;
    end
    return;
end

function lyr_sln = getScore(layers, solutions)
    % Fit for this: https://agriknowledge.affrc.go.jp/RN/2030552727.pdf
    % Display help
    disp("[ INFO ]  Using scoring method.");
    fprintf("\n");
    disp("In this mode, you will enter the score of criteria for each solution.");
    disp("You can also tell the program the ""effect"" of the score.");
    fprintf("\n");
    disp("For example, if the more the score under """ + layers(1) + """, the worse, please input ""0"",");
    disp("other number will be considered positive.");

    % Get input
    len_y   =  length(layers);
    len_s   =  length(solutions);
    evmat   =  zeros(len_y, len_s);
    effect  =  zeros(len_y, 1);
    for n = 1 : len_y
        e = input("The effect of layer """ + layers(n) + """ is (positive: not 0, negative: 0) ?  ");
        if e == 0
            effect(n) = -1;
        else
            effect(n) = 1;
        end
        for m = 1 : len_s
            evmat(n, m) = input("Criteria: """ + layers(n) + """. What is the score for solution """ + solutions(m) + """?  ");
        end
        fprintf("\n");
    end


    % Make evmat become ratio matrix lyr_sln

    % Get each line's average
    avges = zeros(len_y, 1);
    for n = 1 : len_y
        avges(n) = sum(evmat(n, :)) / len_s;
    end

    % Get e block's value
    e_block = zeros(len_y, len_s);
    for n = 1 : len_y
        for m = 1 : len_s
            e_block(n, m) = (evmat(n, m) - avges(n)) / avges(n);
        end
    end

    % Get cs
    cs = zeros(len_y, 1);
    for n = 1 : len_y
        cs(n) = max(abs(e_block(n, :)));
    end

    % Fill the matrix lyr_sln
    lyr_sln = zeros(len_y, len_s);
    for n = 1 : len_y
        for m = 1 : len_s
            lyr_sln(n, m) = 1 + effect(n) * e_block(n, m) * (1 / cs(n));
        end
    end
end

**Comment by 4086606** [comment]
I have added these operators in my upcoming changes. Your Textmate scope selector only applies to everything that isn't a function, string, operator etc.

Try an array with `["meta.function.matlab","meta.function.matlab *"]`
