### ISSUE TITLE
Syntax highlighting incorrect if there is one single quote in a line comment

### ISSUE THREAD

**Issue by chrisalexander** [Gimly/vscode-matlab#14]
Hi, noticed this one this morning, not sure if it is with this extension or VSCode:

![image](https://cloud.githubusercontent.com/assets/50909/24095772/80742742-0d56-11e7-90b5-85057fe57c1c.png)

Cheers

Chris

**Comment by Gimly** [comment]
This issue has been fixed in version 0.6.0. Please re-open if you feel that it has not been correctly fixed.
