### ISSUE TITLE
can't use linter in 2.20

### ISSUE THREAD

**Issue by peter-liuseu** [Gimly/vscode-matlab#140]

**Comment by Gimly** [comment]
OK, I must have messed up something while publishing, I'll take a look, thanks.

**Comment by rlivings39** [comment]
Curious. If you open the Output window and go to "Log (Extension Host)" and scroll around, you don't see the errors that @mjdshibly reported? 

I reliably see those. Syntax highlighting works, but the other providers are then broken. Some other folks I work with have reported similar issues.

**Comment by SNDST00M** [comment]
I found the problem and I'm planning a new release to fix it.
I am also hammering together a test suite so this doesn't repeat itself.

**Comment by SNDST00M** [comment]
Good news, I have made a breakthrough with the testing and will have this out by tomorrow.

**Comment by SNDST00M** [comment]
Hi these issues have been addressed in the latest version! Please notify us if not

**Comment by M00TSDNS** [comment]
#174 allows us to officially use the bundler again.. In particular we have the confidence that we are not depending on Node modules or modules invoked from VS Code itself (which the core team have actively endeavoured to prevent etxdevs from using).
