### ISSUE TITLE
Outline says No Symbols Found in document 'xxx.m' with v.2.2.0

### ISSUE THREAD

**Issue by ohgo1977** [Gimly/vscode-matlab#141]
Hi Xavier,

Firstly, I like to thank you for providing such a nice program.

I found that Outline says 'No Symbols Found f]in document 'xxx.m'' with v.2.2.0.
By downgrading to v2.0.1, the issue is gone.

I am glad if you can check this issue.

Thank you again,
Kosuke

**Comment by SiFreZi** [comment]
I have the same issue with all *.m files

**Comment by M00TSDNS** [comment]
There was a bug in the definition provider but it's now fixed.
Technical explanation in #172.
Please sub to #174 and also try this hack - https://github.com/Gimly/vscode-matlab/issues/157#issuecomment-1088529259 - to fix it immediately.
