### ISSUE TITLE
ctrl+click to open function not working in 2.2.0 

### ISSUE THREAD

**Issue by rick3rt** [Gimly/vscode-matlab#143]
Hi, thanks for the update, the improved grammar works quite nicely. 
However, with the update, the ability to ctrl+click a function name to open that function if its in the same project broke. 

This was very convenient. For now I am reverting to 2.0.1.

**Comment by niharG8** [comment]
I have also been seeing this issue with 2.2.0 and 2.2.1. I reverted to 2.0.1 since this feature is the most useful part of the plugin

**Comment by M00TSDNS** [comment]
I have fixed this in the new pull. Appreciate the push on that.
