### ISSUE TITLE
Go to definition  is not working

### ISSUE THREAD

**Issue by yanjin23** [Gimly/vscode-matlab#147]
this feature just works for 2.0.0 and 2.0.1 not furthermore!
2.2.0 has no "Go to definition" feature
2.2.1 has it, but not working
seems something has been rollbacked!

**Comment by rahulchem** [comment]
Yes same for me. I had it working previously but recently, it has stopped working. Not sure what happened.

**Comment by SiFreZi** [comment]
Same for me:
![image](https://user-images.githubusercontent.com/39189215/142575202-4ff54410-660e-4290-8d1d-0d76c98fcf09.png)

**Comment by SNDST00M** [comment]
Will be fixed when `vscode-textmate-languageservice@0.2.0` lands:

https://user-images.githubusercontent.com/82655227/140609895-bec02678-156f-4212-a460-ff75bceda3e7.png
