### ISSUE TITLE
Extension v2.3.0 becomes unresponsive

### ISSUE THREAD

**Issue by fschwaiger** [Gimly/vscode-matlab#152]
```
[2021-12-15 13:06:33.799] [renderer8] [warning] UNRESPONSIVE extension host, 'Gimly81.matlab' took 98% of 3079.676ms, saved PROFILE here: 'file:///var/folders/vt/l5v0pvrx21s0r239h0zylz2r0000gn/T/exthost-8a6262.cpuprofile' 
[2021-12-15 13:07:13.004] [renderer8] [warning] UNRESPONSIVE extension host, 'Gimly81.matlab' took 63% of 7642.598ms, saved PROFILE here: 'file:///var/folders/vt/l5v0pvrx21s0r239h0zylz2r0000gn/T/exthost-4b14e9.cpuprofile' 
```

Here is the cpu profile: 
[exthost-8a6262.cpuprofile.zip](https://github.com/Gimly/vscode-matlab/files/7719219/exthost-8a6262.cpuprofile.zip)

This did not occur until a few days ago, so I suspect a recent change, which could be v2.3.0.

**Comment by SNDST00M** [comment]
What's concerning here is that the slowdown is actually being caused by the new syntax selector parser based on Atom. This was actually proposed for VS Code in microsoft/vscode-textmate#52 and I was investigating having this parser work in WASM over at peggyjs/peggy#222 but I cannot promise anything other than reverting that huge upgrade in scope power.

This is a significant setback and I'm disappointed to see it happen :(

**Comment by SNDST00M** [comment]
Okay actually its the parser as written by the MS Atom team that is slow on low-end CPUs in anything other than WASM. I will have to reimplement the entire thing in Rust and spin up the branch with that perf boost this weekend.

**Comment by SNDST00M** [comment]
Added caching instead of the Rust thing, it worked! Fix soon:tm:

**Comment by fschwaiger** [comment]
Thank you!

**Comment by SNDST00M** [comment]
Actually do you have NPM on your computer? You could:

0. Go back to 2.3.0 for the extension version.
1. Open `~/.vscode/extensions/gimly81.matlab-2.3.0` in VS Code
2. run `npm install vscode-textmate-languageservice`

And see if the CPU issue is resolved?

**Comment by fschwaiger** [comment]
Did as you asked; for now it looks fine.

**Comment by SNDST00M** [comment]
Update to 2.3.1 to resolve this!

**Comment by M00TSDNS** [comment]
I will be posting a postmortem for the performance issues from my library in #171.
