### ISSUE TITLE
Extension shows excessive activity

### ISSUE THREAD

**Issue by Jamen1993** [Gimly/vscode-matlab#153]
Hello everybody,

I recently got a problem with the extension that I didn't notice before. It may be related to one of the recent VS Code or extension updates.

The problem shows in the following ways:
- syntax highlighting is very slow
- saving *.m files takes much longer when the extension is enabled
- extension host utilises a logical core to capacity after saving for quite some time

I'm currently using V2.3.0 and the problem vanished after downgrading to V2.2.1.

Please request any additional information. Sadly, it's the only way that I'm able to contribute to this extension.

**Comment by tgaochn** [comment]
Same problem for V2.3.0. 
Downgrading to V2.2.1 is a solution for now.

**Comment by MlHsieh** [comment]
Same problem for V2.3.0 on Win 10. CPU usage is abnormally high whenever this extension is enabled.
Downgrading to V2.2.1 resolved the problem.

**Comment by SNDST00M** [comment]
Explanation in #152, I can get a rapid fix ready by tonight.

**Comment by SNDST00M** [comment]
Okay I got the new providers running smoothly on AMD Athlon X2 220, so this should resolve the issue!

**Comment by SNDST00M** [comment]
Temporary workaround while we patiently wait for 2.3.1 to land:

https://github.com/Gimly/vscode-matlab/issues/152#issuecomment-999000997

**Comment by SNDST00M** [comment]
Update to 2.3.1 to resolve this!

**Comment by M00TSDNS** [comment]
This wasn't fully addressed by #154 unfortunately but what did work was a full rewrite of the underlying library.
Please sub to #174 and also try this hack - https://github.com/Gimly/vscode-matlab/issues/157#issuecomment-1088529259 - to fix it immediately.
