### ISSUE TITLE
if, else, end one liners disrupt the outline

### ISSUE THREAD

**Issue by SiFreZi** [Gimly/vscode-matlab#159]
Hello,
```
function printNice(param)
    if param; disp('true'); else; disp('false'); end
    cmd = '@echo nice';
    dos(cmd);
end
```
produces a wrong outline:
![image](https://user-images.githubusercontent.com/39189215/157005593-8a1f5032-3156-4ebe-818b-8fb049f32c03.png)

else and cmd are shown outside the function.

Regards,
Simon

**Comment by SNDST00M** [comment]
Ouch will have to disable folds in `vscode-textmate-languageservice` when they are on the same line.

**Comment by M00TSDNS** [comment]
This one wasn't as critical as the other perf issues, but I spent some time and sketched out a fold algorithm that could handle the issue. It'll be fixed when the pull is merged 😃

**Comment by M00TSDNS** [comment]
FWIW I also killed the ability to generate multiple symbols per line.  
The VS Code team made a design decision to accept the first keyword token as the only important one.
