### ISSUE TITLE
This extension keeps crashing the Extension Host

### ISSUE THREAD

**Issue by sean-omni** [Gimly/vscode-matlab#165]
Even if this is the only active extension it keeps crashing the host. 
VSC 1.68.1
Extension version v2.3.1. Tried regressing to older versions but same thing happens. 

INFO UNRESPONSIVE extension host: starting to profile NOW
WARN UNRESPONSIVE extension host: 'Gimly81.matlab' took 65% of 5242.499ms
Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null

This prevents the Search results updating until host is restarted. Happens frequently but not immediately.

Happens on Windows or Linux.

No linter or matlab paths defined.

**Comment by M00TSDNS** [comment]
Repro'ed in 2.3.1 and fix confirmed in #174.
When a single document is opened and the UI closes that editor to open a new one, the previous document is tokenized at the same time in an infinite loop.
Not sure whether this is delayed by 100ms at a time, but it definitely is clogging up the call stack in a bad way.
