### ISSUE TITLE
Incorrect syntax highlighting for set/get methods in class

### ISSUE THREAD

**Issue by zealotrush** [Gimly/vscode-matlab#17]
The set/get methods in MATLAB class files have incorrect syntax highlighting. Please see the picture below.

![vscode-matlab-syntax-highlighting](https://user-images.githubusercontent.com/2275580/27811831-e51a1384-609c-11e7-9329-3422d7b6ba77.png)

The color scheme used here is *Dark+ (default dark)*, but this issue applies for most of the color schemes -- as long as it uses different colors for function names and function arguments.

**Comment by Gimly** [comment]
Just to be sure, in that case, "set.param" should be selected as a function name, is that correct?

Are there other cases of "." being part of a function name?

**Comment by Gimly** [comment]
This issue has been fixed in version 0.6.0. Please re-open if you feel this hasn't been correctly fixed.
