### ISSUE TITLE
Extremely slow: Go to Definition F12 or Peek Definition

### ISSUE THREAD

**Issue by DoctorDro** [Gimly/vscode-matlab#172]
Dear Hahn Xavier,
first of all thank you for the great work and for sharing with all of us. I find myself quite often right-clicking and choosing "Go to Definition". However, it takes several seconds for this operation to complete although Control-Find the name of the function works like a charm. Is it a performance problem, wrong implementation or what? You have the list of functions from the top up menu, so why does this terrible slow down happen? Peek definition is also quite slow. It seems you are trying to create the list of function first although you already have them in the top {} methods > menu.

Additionally quite useful would be (if is it possible to implement that) the "Find all References" of a member method or variable. 

Thank you for the great work, and all best wishes.

**Comment by M00TSDNS** [comment]
FWIW the code issue is in the library that was used to implement the LSP features.

A quick postmortem:

- The problem originated from `vscode-textmate-languageservice@0.2.3`.
- VS Code doesn't cut bad requests gracefully in its file finder.
- The glob used to search for other files in the definition provider was broken.
  (It was looking for `./*your function name here*.m`, not `./**/*your function name here*.m`.)
