### ISSUE TITLE
switch syntax highlighting issue

### ISSUE THREAD

**Issue by daewon-lee** [Gimly/vscode-matlab#176]
syntax highlight when using *switch* seems to have some issues when paired with structures or group of cases.

- If *switch* condition is based on member property of a class or structure, then the paired *end* syntax coloring gets broken. See example below. The *end* in line 11 should be colored purple, and seems to have an issue with text token pair identification when using structures or class properties. Because of this the syntax highlighting for the rest of the code gets corrupted.
![image](https://user-images.githubusercontent.com/70240637/219493416-044af0ab-59ac-4a73-97d3-d14a01ddcca7.png)

- If the case condition of a switch uses grouping with braces { }, then similar matching pair right brace is not correctly identified and highlighting gets corrupted. See example below. The right brace in line 6 should be colored red.
![image](https://user-images.githubusercontent.com/70240637/219493507-01547e36-10c9-4452-8f6a-cdd51318e343.png)

- The following is an example of a normal expected case.
![image](https://user-images.githubusercontent.com/70240637/219493583-f86db7c9-2309-4b8f-ad0c-47f27be06ab9.png)

**Comment by M00TSDNS** [comment]
An issue needs to be raised upstream at - https://github.com/mathworks/MATLAB-Language-grammar/commit/58ecf4f864b8b6b0dca32328beaa351fcc561fb1

**Comment by daewon-lee** [comment]
Thanks. Created issue in upstream https://github.com/mathworks/MATLAB-Language-grammar/issues/47

**Comment by daewon-lee** [comment]
Understood. Re-opening the issue for tracking purposes.

**Comment by daewon-lee** [comment]
Issue have been closed in upstream. Closing issue.
