### ISSUE TITLE
Symbol Support?

### ISSUE THREAD

**Issue by senften** [Gimly/vscode-matlab#18]
Would it be possible to add symbol support, at least for functions?

**Comment by Gimly** [comment]
What are symbol? In what way are they not supported and how would you like to have the support?

**Comment by senften** [comment]
I'd like to navigate to symbols, https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol

Using the matlab extension, I get

![vsc_matlab_capture](https://user-images.githubusercontent.com/288909/29141794-504e3e52-7d15-11e7-942d-17d5067a8247.PNG)

My expectation is more along the lines of what I see with C#

![vsc_csharp_capture](https://user-images.githubusercontent.com/288909/29141827-72ae0428-7d15-11e7-8f59-c9db51bf3855.PNG)

**Comment by amauragis** [comment]
Was thinking about this this morning for whatever reason...

It looks like this is the path forward: https://code.visualstudio.com/docs/extensionAPI/language-support

We either transition to a language server, or [add code to provide DocumentSymbolProviders](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages).

Writing regexes to match the function declarations probably wouldn't be too hard.  You'd have to match:
```
function [a, b, c] = foo(bar)
function a = foo(bar)
function foo(bar)
```

**Comment by Gimly** [comment]
Finally have some time to give this extension some love, I've started implementing the document symbol provider, added it into a branch.
Besides the functions, are there any other symbols which would make sense for Matlab?

**Comment by amauragis** [comment]
The reference I was hoping to match is the support in ST3
![image](https://user-images.githubusercontent.com/2589199/30965178-6b93d74c-a422-11e7-8524-9f7b3f08b164.png)

It looks like they currently only do function lookup.  In this [Atom issue](https://github.com/atom/symbols-view/issues/26) they reference ST3 scanning the syntax for things with the "meta.function" key, which might be a good approach.

Another possible reference is the ctags implementation for matlab [here](https://github.com/universal-ctags/ctags/blob/master/parsers/matlab.c)

**Comment by Gimly** [comment]
Go To Symbol are now supported by the version 0.7.0.

**Comment by Gimly** [comment]
@senften Did you test the Go to symbol option? Are you satisfied with it or would you like to add/change something? If everything is fine, please close the issue, thanks 😄.

**Comment by Gimly** [comment]
Closing the issue since the feature was implemented in 0.7. If you find a bug or would like to improve it, please open a new issue. Thanks !

**Comment by senften** [comment]
Sorry, I missed this and I didn't realize that I was supposed to close it.
My apologies. I updated my visual studio code the other day. So far so
good. I move back and forth between Matlab and VS Code.

Thanks for the quick response.

**Comment by Gimly** [comment]
No worries, glad you like the new version. Don't hesitate to ask for more 😃.
