### ISSUE TITLE
Use checkcode instead of mlint

### ISSUE THREAD

**Issue by kdheepak** [Gimly/vscode-matlab#26]
MATLAB recommends using `checkcode` instead of `mlint` now.

https://www.mathworks.com/help/matlab/ref/mlint.html

https://www.mathworks.com/help/matlab/ref/checkcode.html

**Comment by sco1** [comment]
`checkcode` is not an externally executable file like `mlint`, so it would require interfacing directly with MATLAB in order to run.

**Comment by Gimly** [comment]
Hi @kdheepak, thanks for your suggestion!

As @sco1 explained, `checkcode` is an internal method, unlike `mlint.exe` that is used by this extension. If we wanted to use the internal method we'd have to interface directly with Matlab which, at the current state of Matlab would be quite difficult, especially if we want to make it cross-platform.

Moreover, there would be absolutely no advantage as both methods give the exact same output. I think the recommendation on the mathworks website is more aimed at when people use the method in Matlab and not for our use case.

I'm going to close this issue for now as I don't think it's really worth working on this. Feel free to continue the conversation if you disagree or have other information that would make it more worthwhile.

Thanks again for your proposition.

**Comment by kdheepak** [comment]
Thanks! You are both correct, sorry I should have looked into it in more detail before posting!
