### ISSUE TITLE
Quite good! I appreciate your work!

### ISSUE THREAD

**Issue by tigert1998** [Gimly/vscode-matlab#27]
It's not an issue actually. xD
Wish you would develop more functions of this extension in the near future.

**Comment by Gimly** [comment]
Thanks for the feedback, it's really appreciated. I will definitely continue to develop new functions for the extension, if you have ideas don't hesitate to create a new issue with your feature idea.

Unfortunately it's a side project, and as all side project I have limited resources to put into it, so new features don't come as fast as I'd like them to. But eventually they do get there 😄. I'd be very happy to get some help to add new features though.

Closing the issue as, it's not really an issue, but thanks a lot!

PS: You can also show you're liking of the extension by rating it on the extension marketplace. Thanks!
