### ISSUE TITLE
No support for classdef/properties... keywords

### ISSUE THREAD

**Issue by zealotrush** [Gimly/vscode-matlab#3]
Keywords like `classdef`, `properties`, etc, are not recognized. Could you please add those keywords? Thanks!

**Comment by Gimly** [comment]
That's really weird, but you're right. I'm going to have to check why those keywords are absent. Do you know if they are part of some kind of subset of Matlab?
Something that appeared in a recentish version of Matlab?

Thanks

**Comment by zealotrush** [comment]
Those keywords are part of the OOP feature, which was added in version R2008a. Related keywords include: `classdef`, `properties`, `methods` (also a function name), `events`.

**Comment by Gimly** [comment]
Fixed in version 0.3.0
