### ISSUE TITLE
Transpose operator(') vs quotes ('')

### ISSUE THREAD

**Issue by Slyran** [Gimly/vscode-matlab#33]
Dear author:
I find the code will be highlighted incorrectly if there is **'** as transpose operator, like

![image](https://user-images.githubusercontent.com/19568832/35135946-60d43876-fcae-11e7-86b4-680e9617a971.png)

**Comment by Gimly** [comment]
Thanks, that's likely due to the text parsing regex that doesn't stop how it should.

**Comment by sco1** [comment]
What version of the plugin are you using? I don't see this behavior with `0.8.0`

```
B = A';
a = 2;
```

Produces:

![capture](https://user-images.githubusercontent.com/5323929/36554017-f4b0856c-17cb-11e8-8ceb-71d8ff4ed620.PNG)

**Comment by Gimly** [comment]
Just tried and indeed it's working correctly with the latest version. I recall we had some big issues with comments in  a previous version that was fixed. @Slyran could you please check that you have the latest version and try again?

**Comment by Slyran** [comment]
Works perfectly now. Thanks for the effort! :)

**Comment by Gimly** [comment]
You're welcome!
