### ISSUE TITLE
"AddParameter" highlighting issue

### ISSUE THREAD

**Issue by hongkai98** [Gimly/vscode-matlab#34]
![1](https://user-images.githubusercontent.com/1357113/35666590-a03c5d92-0765-11e8-9f2d-ee0768c57e62.jpg)
![2](https://user-images.githubusercontent.com/1357113/35666602-ac297e32-0765-11e8-87d8-f409ce970fe8.jpg)

Hi @Gimly ,

Just found a little highlighting problem here. Since "AddRequired" and "AddOptional" can be highlighted properly, could you please make "AddParameter" highlighted as well? 

Thank you!

**Comment by sco1** [comment]
@hongkai98 for future reference it would be helpful to include a copy/pastable code block so folks don't have to type from a picture.

@Gimly would you prefer adding `addParameter` to the syntax definition with a PR against [Textmate](https://github.com/textmate/matlab.tmbundle/blob/master/Syntaxes/M.tmLanguage#L633) or local to [this extension](https://github.com/Gimly/vscode-matlab/blob/master/syntaxes/matlab.tmLanguage#L633)?

**Comment by Gimly** [comment]
@sco1 Please add it here, the Textmate import was a one-time thing, and the two extensions have diverged a lot so there's little value in re-doing the import.

**Comment by Gimly** [comment]
Fixed in version 0.8.1
