### ISSUE TITLE
mlint location setting for multiple OS

### ISSUE THREAD

**Issue by Pygex** [Gimly/vscode-matlab#36]
Hi, I am using matlab on both my windows PC and mac laptop. I use an extension to keep my extensions and settings synced between the devices for conveniency, but as the paths for the matlab are totally different, I cannot have the mlint function nicely with the automatic updating of the user settings.

Is there a way to define a OS specific setting or can you add extra settings entries for the mlint path? Like:

matlab.linux.mlintpath
matlab.mac.mlintpath
matlab.windows.mlintpath

**Comment by sco1** [comment]
What extension are you using to sync? [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) has [local overrides](https://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html)

**Comment by Pygex** [comment]
Ah, thank you! I did not now one could do that whit it ^.^

**Comment by Gimly** [comment]
I don't think this is something that the extension should care about, it's a very specific need and it would make the installation / configuration less simple for most users. 

I will close this issue, if you don't agree please re-open it with more information. 

Thanks for your help.
