### ISSUE TITLE
Update function definitions for syntax highlighting

### ISSUE THREAD

**Issue by sco1** [Gimly/vscode-matlab#38]
Textmate's syntax was last updated in December 2015, so there are a good amount of missing functions that have been added since then or weren't included in the first place.

MATLAB's documentation maintains both a [categorized function list](https://www.mathworks.com/help/matlab/functionlist.html) and an [alphabetical function list](https://www.mathworks.com/help/matlab/functionlist-alpha.html). It also does so separately for toolbox-specific functions (e.g. [Image Processing Toolbox](https://www.mathworks.com/help/images/functionlist-alpha.html)). It would probably be worthwhile to come up with a method to scrape these and update `matlab.tmLanguage` in a relatively automated fashion.

**Comment by sco1** [comment]
I've added a basic scraper and generated a preliminary dump for all R2017b toolboxes I have access to here:

https://github.com/StackOverflowMATLABchat/MATLABfcnscrape

**Comment by Gimly** [comment]
Sorry I haven't answered earlier. Thanks a lot for that work. I'm not quite sure about the reasons for the different coloring, it's probably some scories that are still here from the import process. I'd rather have something meaningful and we should try to start working on your scraping and define which functions make sense to add and how.

**Comment by Gimly** [comment]
@sco1 Sorry, but what's the status on this issue ? Is the "new" syntax file with the list of functions up to date?

**Comment by sco1** [comment]
Not beyond R2018a, the scraping is pretty fragile so it broke when TMW updated how they render the online documentation for R2018b+. Since it's been mostly a curiosity project with nobody dependent on a fix I've only done some low-effort exploration into updating the scraper.

I just started reading the discussions related to the new syntax grammar, I've been a bit behind. From a cursory read, from a sustainability perspective I'm inclined to agree with the rationale for not including explicit function highlighting but I'm happy to take another look at refreshing the function dump if it's something you'd like to pursue.

**Comment by Gimly** [comment]
@rlivings39 has been kind enough to help us by creating [another syntax file ](https://github.com/Gimly/vscode-matlab/blob/master/syntaxes/matlab-functions.tmLanguage) for the functions. This way, even though the official syntax doesn't support function highlighting, we do :).

Now the file has been created using the old syntax and it's probably pretty outdated. So it could be interesting to use your scrapper to update the syntax file.

**Comment by sco1** [comment]
Very cool, I missed that!

I'm traveling a bit near-term but I will try and take a look within the next couple weeks.

**Comment by Gimly** [comment]
No worries, there's no rush, I haven't had much time to work on this extension myself lately.

**Comment by sco1** [comment]
Should be more or less updated for R2019a now. I've done a [first pass](https://github.com/StackOverflowMATLABchat/MATLABfcnscrape/tree/master/JSONout/R2019a) but haven't gone through and inspected too critically yet. There are a couple things that I've noticed for tweaks but unless I've missed something glaring the output shouldn't change a whole lot.

**Comment by sco1** [comment]
This is well out of scope now so I'm going to go ahead and close. Since the grammar is now first-party via https://github.com/mathworks/MATLAB-Language-grammar they're probably best equipped to keep everything up to date :)
