### ISSUE TITLE
How would one initialize the path for the mlint path for mac OS X on vscode

### ISSUE THREAD

**Issue by dayuu4** [Gimly/vscode-matlab#4]
Since the path on windows will look like this:
"matlab.mlintpath": "C:\\Program Files (x86)\\MATLAB\\R2012a\\bin\\win32\\mlint.exe",
What would the path for mac osx be?

Thanks

**Comment by Gimly** [comment]
I'm not quite sure how you can get the path to an application in OSX as I've never used it.

It could be something like: `/Applications/MATLAB_RXXXx.app/bin/matlab`

**Comment by Gimly** [comment]
Did it work? Since I don't have any news from you, I'm going to close the issue.

**Comment by marcelfarres** [comment]
I have the same issue and I can't make it work.

**Comment by Gimly** [comment]
So, is it working? Do you get the linter to trigger on save? If it does work I'll update the help with your path.

**Comment by marcelfarres** [comment]
Yep, I get the linter warnings onSave :) 

Thanks for this extension!

**Comment by marcelfarres** [comment]
Can you edit also https://marketplace.visualstudio.com/items?itemName=Gimly81.matlab ?

**Comment by Gimly** [comment]
I'll do, yes, but for that I need to publish a new version, and I have a few things that I haven't fully tested yet.
I don't have access to a Matlab license at the moment, so it kind of complicates the work, but I'll try to get something done this week or next week :).
