### ISSUE TITLE
Support for MLint Config Settings

### ISSUE THREAD

**Issue by JamieSharpe** [Gimly/vscode-matlab#41]
Hello,

This is a great extension and has helped me out a lot, especially where the matlab IDE fails.

Is it possible to add another parameter to the mlint options that pass in a `settings.txt` file?

From the [mlint docs](https://uk.mathworks.com/help/matlab/ref/mlint.html) it supports the following:

> `mlint('filename','-config=settings.txt')`

A settings file can be generated from the matlab IDE Home>preferences>Code Analyser:
![matlab_2018-03-24_13-18-45](https://user-images.githubusercontent.com/1139365/37864400-21c07fc4-2f66-11e8-9afa-131348d469ec.png)

Which when saved will produce the following file:
`MLintSettings.txt`
```
# Copyright 2018 The MathWorks, Inc.

0NO4LP
```

Currently to suppress warnings, you need to add `%#ok` at the end of the line:

![code_2018-03-24_13-24-47](https://user-images.githubusercontent.com/1139365/37864453-0a82ae4e-2f67-11e8-9bff-33778adec783.png)
 
Removing that comment produces this problem:

![code_2018-03-24_13-25-07](https://user-images.githubusercontent.com/1139365/37864462-1c24ec02-2f67-11e8-9287-7eee4b7807a4.png)

With mlint and the `MLintSettings.txt` passed in, that problem will be suppressed without the additional comment.

Would it be possible to add a config option that can take the path to a `MLintSettings.txt` file to be used in the process?

**Comment by Gimly** [comment]
Thanks for the proposal, will definitely take a look at that.

**Comment by Gimly** [comment]
It seems that the mlint.exe utility that I'm using for the linting doesn't support the -config parameter, or at least I can't have any info on how I can pass a config file to it.

Unfortunately, for now, I'm stuck with using this linter that is not documented, and it looks like it doesn't have all the features of the mlint command.

**Comment by sco1** [comment]
Tracing `checkcode` ends up with a call to the `mlint` MEX file with the default parameters being:

```
mlintmex('-config=/path/to/MLintSettings.txt', '/path/to/mfile.m') 
```

It doesn't seem like `mlint` does any parsing of this, as using the `-config=''` flag seems to work fine with the external linter (on Mac at least):

Default:
```
>> ./mlint -config="/path/to/default/MLintSettings.txt" "/path/to/mfile.m" 
L 1 (C 3): Terminate statement with semicolon to suppress output (within a script).
```

And modifying the MLint settings to ignore this error:
```
>> ./mlint -config="/path/to/MLintSettingsTest.txt" "/path/to/mfile.m"
```

Returns nothing, as expected
