### ISSUE TITLE
Auto-indentation not working?

### ISSUE THREAD

**Issue by roschtatoschta** [Gimly/vscode-matlab#44]
Hi,

this is a great bundle, but one thing is driving me nuts: auto-indentation does not work for me at all.

For example, after a line starting with "if ..." it does not automatically indent the next line and if I do the indentation manually, it does not automatically un-indent the "end" line. Problem occurs for all flavours of typically indented expressions (if, switch, for, ...), but only for Matlab code. Ruby for example works fine.

Since there are indentation rules in the Matlab configuration files I assume that auto-indentation should work using this bundle? Is this a known problem or something partivular to my setup? Bundle has been re-installed, didn't help.

Cheers,

Carsten

**Comment by Gimly** [comment]
I have to do a few tests with that. I'm pretty sure it was working before, maybe something changed with more recent versions of VSCode.
