### ISSUE TITLE
Chinese support?

### ISSUE THREAD

**Issue by OpportunityLiu** [Gimly/vscode-matlab#5]
![屏幕截图(2).png](https://ooo.0o0.ooo/2016/07/08/578073cd88458.png)
I'm using VS Code 1.30 and Matlab 2016a.

**Comment by Gimly** [comment]
Ouch, that will be a pain to test :)

Could you send me a few outputs of mlint in Chinese? This way I'll be able to test it. It's probably simply an issue with the encoding.

Thanks!

**Comment by OpportunityLiu** [comment]
Test code:
```
load sunspot.dat
year = sunspot(::,1);
relNums = sun spot(:,2);

plot(year,relNums...
))
title(Sunspot Data)
```

Output:
```
L 2 (C 17): ':' 处的语法无效。可能缺少 a )、} 或 ]。
L 2 (C 18): 在 ',' 处出现解析错误: 使用的 MATLAB 语法可能无效。
L 2 (C 20): 在 ')' 处出现解析错误: 使用的 MATLAB 语法可能无效。
L 3 (C 15-18): 在 spot 处出现解析错误: 使用的 MATLAB 语法可能无效。
L 3 (C 23): 在 ')' 处出现解析错误: 使用的 MATLAB 语法可能无效。
L 6 (C 2): 在 ')' 处出现解析错误: 使用的 MATLAB 语法可能无效。
L 7 (C 15-18): 'Data' 处的语法无效。可能缺少 a )、} 或 ]。
```

**Comment by Gimly** [comment]
Awesome, thanks. I'll try to work on this asap.

**Comment by Holie** [comment]
Hi I just used your updated code(by changing my matlabDiagnostic.js file) but it still does not work. :(
