### ISSUE TITLE
Could not find path to the matlab executable

### ISSUE THREAD

**Issue by jialinyi94** [Gimly/vscode-matlab#50]
First, thanks for such a great extension. 

I am using MATLAB_2017b on OS X version 10.13.4. When I tried to run M file using your extension,
it throws error: 

> Could not find path to the matlab executable.

Could you help me check what is going on?

Below is my user-setting

```
{
    "workbench.colorTheme": "One Dark Pro",
    "matlab.mlintpath": "/Applications/MATLAB_R2017b.app/bin/maci64/mlint"
}
```

Thank you and kind regards,

Jialin

**Comment by Gimly** [comment]
Could you please check that the mlint app is present in the maci64 folder?

**Comment by jialinyi94** [comment]
Sure, as I checked the in "/Applications/MATLAB_R2017b.app/bin/maci64/mlint", there is a Unix executable file "mlint".

**Comment by Gimly** [comment]
Wait, you have a mlint folder in maci64?

Could you try to put '/Applications/MATLAB_R2017b.app/bin/maci64/mlint/mlint' for the value?

**Comment by jialinyi94** [comment]
If I change to 

```
{
    "workbench.colorTheme": "One Dark Pro",
    "matlab.mlintpath": "/Applications/MATLAB_R2017b.app/bin/maci64/mlint/mlint"
}

```

> Cannot find mlint at the given path, please check your configuration file.

**Comment by sco1** [comment]
If the original error message is correct, your user settings need to be:

```
{
    "workbench.colorTheme": "One Dark Pro",
    "matlab.matlabpath":"/Applications/MATLAB_R2017b.app/bin/maci64/MATLAB",
    "matlab.mlintpath": "/Applications/MATLAB_R2017b.app/bin/maci64/mlint"
}
```

**Comment by jialinyi94** [comment]
Sorry for the late reply. I tried but it still doesn't work.

```
{
    "workbench.colorTheme": "One Dark Pro",
    "workbench.iconTheme": "vscode-great-icons",
    "matlab.matlabpath":"/Applications/MATLAB_R2017b.app/bin/maci64/MATLAB",
    "matlab.mlintpath": "/Applications/MATLAB_R2017b.app/bin/maci64/mlint"
}
```

Here is my setting.

**Comment by SheldonZhong** [comment]
We are little confused by your description. 

1. VS Code MatLab extension does NOT support run `.m` file in VS Code. According to your description, a prompt is shown 

> Could not find path to the matlab executable.

That should be reasonable for the fact that this extension actually could not execute a `.m` file.

2. We couldn't find anywhere in source code throws a error like
> Could not find path to the matlab executable.

But we do have 
> Cannot find mlint at the given path, please check your configuration file.

So your description in 

> If I change to
> 
> {
>     "workbench.colorTheme": "One Dark Pro",
>     "matlab.mlintpath": "/Applications/MATLAB_R2017b.app/bin/maci64/mlint/mlint"
> }
> 
> > Cannot find mlint at the given path, please check your configuration file.

should be natural.

3. For the configuration here
> Sorry for the late reply. I tried but it still doesn't work.
> 
> {
>     "workbench.colorTheme": "One Dark Pro",
>     "workbench.iconTheme": "vscode-great-icons",
>     "matlab.matlabpath":"/Applications/MATLAB_R2017b.app/bin/maci64/MATLAB",
>     "matlab.mlintpath": "/Applications/MATLAB_R2017b.app/bin/maci64/mlint"
> }
> Here is my setting.

it should fix 
> Cannot find mlint at the given path, please check your configuration file.

But
> Could not find path to the matlab executable.

is natural.

**Comment by Gimly** [comment]
I haven't read correctly, the error `Could not find path to the matlab executable` cannot come from this extension, I'm not using anything from the Matlab executable for now, the `matlab.matlabpath` configuration is not used. 

Maybe the error comes from mlint directly? Could you try calling mlint directly from the console line to see what happens? You can call it and simply pass it the path to a .m file.

```Bash
/Applications/MATLAB_R2017b.app/bin/maci64/mlint "path-to/matlab-file.m"
```

**Comment by jialinyi94** [comment]
@SheldonZhong , I see. I didn't expect that this extension does not support execute .m file.

@Gimly I ran this command in Mac's terminal, and it returned nothing.

**Comment by Gimly** [comment]
@jialinyi94 what do you mean it returned nothing, did it return blank? Could you please send a screenshot of the terminal window?

**Comment by Gimly** [comment]
@jialinyi94 Any news on that? Is it fixed?

**Comment by WillGreen98** [comment]
@Gimly, I can confirm this error is not fixed as I issued a new post today, I did not see there was already a thread regarding it. Same situation with no change.

**Comment by WillGreen98** [comment]
@jialinyi94 Found it - https://github.com/eamon-bell/matlab-runner/ That's the package causing the error.
