### ISSUE TITLE
The transpose of a matrix is parsed to a char array

### ISSUE THREAD

**Issue by spinningwatt** [Gimly/vscode-matlab#51]
When typing a single quotation mark to obtain the transpose of a matrix, the extension parses the functions or numbers behind it to a char array incorrectly, then rendering them incorrectly.

![matlabbug](https://user-images.githubusercontent.com/31122455/39660580-99b15574-5074-11e8-8133-1b920bee860d.gif)
the sample code in gif above is correct in Matlab.

**Comment by SheldonZhong** [comment]
![image](https://user-images.githubusercontent.com/12372003/39671459-4eec6998-514b-11e8-865c-5a722f7c0b0e.png)

It works perfect. According to your GIF, even the comment is not recognized correctly. 
My suggestion is to check whether your extension is latest version. 
I guess some extension overrides `.m` file in your case.

**Comment by spinningwatt** [comment]
Thank you. Sorry, it's my fault. The extension works well. My vscode updates it and I didn't reload.
