### ISSUE TITLE
Underlining of unused variable names is off by 1 character.

### ISSUE THREAD

**Issue by FYPetro** [Gimly/vscode-matlab#54]
As seen in the image below, unused variables with more than two characters in length are not underlined correctly.  The end of the wavy green line is off by one character.

![Image illustrating the issue](https://i.stack.imgur.com/pQkNd.png)

**Comment by sco1** [comment]
Did vscode change its highlighting syntax? This seemed to work properly in the past (as evidenced by the linter image in the readme, which also doesn't work properly now)

**Comment by Gimly** [comment]
This issue has ben fixed since a few version if I'm not mistaken. Closing the issue, feel free to reopen if you feel this isn't true.
