### ISSUE TITLE
Highlighting of varargin transposed

### ISSUE THREAD

**Issue by FYPetro** [Gimly/vscode-matlab#56]
Not sure if this is intended, but the `varargin` in `varargin'` is not currently highlighted. See below:

![image](https://user-images.githubusercontent.com/5100887/40699476-1a3a79e6-6407-11e8-9895-fd52312f6272.png)

**Comment by sco1** [comment]
There's an issue with the scope precedence in the TM language spec. If you inspect the TM scope you can see that `varargin` is classified as a function, where `varargin'` is completely captured as a transpose operator and loses the function classification:

<img width="249" alt="varargin" src="https://user-images.githubusercontent.com/5323929/40716738-f760fafa-63d7-11e8-8ecf-7938dcb19ac9.png">

<img width="296" alt="transpose" src="https://user-images.githubusercontent.com/5323929/40716745-fc04aae8-63d7-11e8-819d-15a90a442c10.png">

**Comment by Gimly** [comment]
With version 1.0 we've updated the syntax highlighting syntax which might have been the cause of the issue. Could you please tell me if you still experience the issue with that version?

**Comment by FYPetro** [comment]
This issue has not been resolved with the snippet in the screenshot.
