### ISSUE TITLE
Highlighting comments after ...

### ISSUE THREAD

**Issue by FYPetro** [Gimly/vscode-matlab#57]
The plugin does not highlight text commented out by `...`:

VS Code:
![image](https://user-images.githubusercontent.com/5100887/41212614-cbc9decc-6d71-11e8-8c86-517adec73086.png)

Matlab built-in editor:
![image](https://user-images.githubusercontent.com/5100887/41212635-ed1e687c-6d71-11e8-8590-30bce14b896a.png)

Snippet:
```
% Comment
[a,b] = functionname(c, ...
    ...'Partition', 3, ...
    'Property',  {} ...
    )
```

**Comment by Gimly** [comment]
With version 1.0 we've updated the syntax highlighting syntax which might have been the cause of the issue. Could you please tell me if you still experience the issue with that version?

**Comment by FYPetro** [comment]
With the 1.0.0 update I do not experience this issue with the given code snippet anymore. Text after “…” are correctly marked as comment.

On Mar 28, 2019, at 3:10 PM, Xavier Hahn <notifications@github.com<mailto:notifications@github.com>> wrote:

◆ This message was sent from a non-UWYO address. Please exercise caution when clicking links or opening attachments from external sources.


With version 1.0 we've updated the syntax highlighting syntax which might have been the cause of the issue. Could you please tell me if you still experience the issue with that version?

**Comment by Gimly** [comment]
Great news ! That was quick, thanks for testing and reporting your issue. Hope you like the extension. Cheers!
