### ISSUE TITLE
Double percent symbol comment bug

### ISSUE THREAD

**Issue by SheldonZhong** [Gimly/vscode-matlab#58]
![image](https://user-images.githubusercontent.com/12372003/41477415-cddce924-70f6-11e8-95b4-5dd6471e8ed9.png)

How to reproduce:
1. Type two comment symbols `%%`
2. Append one or more spaces 
3. Next line of code will be wrongly painted in green, like a comment, however it's not.

**Comment by Gimly** [comment]
Is the double percent symbol supposed to mean something?

**Comment by sco1** [comment]
MATLAB uses them to denote [code sections](https://www.mathworks.com/help/matlab/matlab_prog/run-sections-of-programs.html), which can be executed piecewise by the IDE.

From an editor perspective, their behavior is the same as `%`.

**Comment by sco1** [comment]
I'm guessing it has something to do with `meta.cell.matlab` being defined where/how it is. MATLAB cells are delimited by `%%`, but they do contain valid code (see #30 for an example). This doesn't seem to be correctly identified in the case where the `%%` line terminates with one or more spaces or tab (combination of the 2 untested).

If you scope an example similar to the OP, you can see the behavior:

Incorrect:

![image](https://user-images.githubusercontent.com/5323929/46323331-ae61c780-c5bb-11e8-91d9-4895e4da9871.png)

Correct:

![image](https://user-images.githubusercontent.com/5323929/46323304-9be78e00-c5bb-11e8-9a14-2c685d3044c2.png)

That said, the correct-er version would be something like the following:

```
%% double percentage comment line, start Cell (1)
% single percentage comment line AND Cell (1)
Source code AND Cell (1)

%% double percentage comment line, start Cell (2)
% single percentage comment line AND Cell(2)
Source code AND Cell(2)
```

etc.

**Comment by Gimly** [comment]
@sco1 thanks for the heads-up, I'll try to figure out something to separate those two use cases.

By the way, how did you get this window that shows the information?

**Comment by sco1** [comment]
`Developer: Inspect TM Scopes` in the Command Palette

**Comment by zhaouv** [comment]
When I use this in `setting.json` 
![image](https://user-images.githubusercontent.com/26158289/47921313-3dca0580-deef-11e8-9355-66e05fb8aa29.png)
 to highlight comment-title just like matlab IDE. I find this bug and then find this issue.
![image](https://user-images.githubusercontent.com/26158289/47921566-deb8c080-deef-11e8-9c10-48a410a86a54.png)

I will fix it.

**Comment by Gimly** [comment]
Fixed, hopefully definitely this time, in version 1.1.0. If you feel there still is an issue with this, please re-open or open another issue.
