### ISSUE TITLE
Error: "Could not find path to the matlab executable"

### ISSUE THREAD

**Issue by WillGreen98** [Gimly/vscode-matlab#59]
Trying to develop MATLAB scripts with VSCode in addition to Platformio, below are the User Profile Settings to which, the mlint path is as described on the official package documentation.

"matlab.matlabpath": "/Applications/MATLAB_R2018a.app/bin/maci64/MATLAB", or .../bin/matlab
"matlab.mlintpath":  "/Applications/MATLAB_R2018a.app/bin/maci64/mlint",

Is using the binary file incorrect? Should I be pointing to a folder instead?

**Comment by sco1** [comment]
This has come up before in #50 but OP stopped responding. 

This extension currently doesn't use `matlab.matlabpath`, so it won't throw an error related to the MATLAB executable. It's likely the error is either coming from `mlint` or from another MATLAB related if you have one.

We can probably pick up [here](https://github.com/Gimly/vscode-matlab/issues/50#issuecomment-384898574) where the last OP left off and work on figuring out what's going on.

**Comment by WillGreen98** [comment]
Found it - https://github.com/eamon-bell/matlab-runner/ That's the package causing the error.
