### ISSUE TITLE
Linter issue in file switching

### ISSUE THREAD

**Issue by Furqan136** [Gimly/vscode-matlab#66]
When I write code and save the linter works fine (Though update on type rather than save would be awesome) but when I open more than one matlab files an issue occurs. When I switch from file1 to file2 and type something and save that, the warnings on file1 go away and don't come back even when I switch back to file1. They are also not shown on save rather they are show when file is changed and then saved and when that happens, file2 gets the same issue. Please fix this.

**Comment by Gimly** [comment]
Thanks for reporting this issue, I'll take a look
