### ISSUE TITLE
Highlighting issue when using nested comments

### ISSUE THREAD

**Issue by AnnyCaroline** [Gimly/vscode-matlab#69]
Hi, 

![image](https://user-images.githubusercontent.com/17753656/51792271-e659cf80-2195-11e9-9b50-3ec94214dec2.png)

The highlight of nested comments does not seem to work correctly

**Comment by SheldonZhong** [comment]
This issue is repetitive of #31.

**Comment by AnnyCaroline** [comment]
It doesn't seem to be a repetitive issue.

**Comment by Gimly** [comment]
@AnnyCaroline You're right, the issue isn't exactly the same. @rlivings39 has opened an issue for the official grammar, I'll include the fix as soon as they have fixed the issue on their side.

**Comment by Gimly** [comment]
Version 1.1.0 should fix this issue which was fixed on Mathwork's official grammar.
