### ISSUE TITLE
Unable to display Chinese characters correctly in Windows

### ISSUE THREAD

**Issue by jerrychong25** [Gimly/vscode-matlab#70]
Hi all,

I would like display Chinese language character for **MATLAB** files (_.m_) in Visual Studio Code.

I have followed https://github.com/Gimly/vscode-matlab/blob/master/README.md and  https://github.com/Gimly/vscode-matlab/issues/16 instruction to set `"matlab.linterEncoding" : "gb2312"` in settings.json, as per below:
![2](https://user-images.githubusercontent.com/15714095/53781727-f14a1180-3f44-11e9-9819-927a3de7cc47.JPG)

However, the issue still appeared, as per below:
![1](https://user-images.githubusercontent.com/15714095/53781790-44bc5f80-3f45-11e9-8cac-6b784db6a2d7.JPG)

My Windows 7 laptop default language is **English (Malaysia)**.

**VS Code Version Details**
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Could anyone assist on this issue?

Thanks.

**Comment by SheldonZhong** [comment]
This is problem is not related to the plugin itself. You could easily fix it by clicking the bottom-right position of VS Code windows, and there will be a button `UTF-8` by default. You could click it and it will prompt to select an action, choose `Reopen with Encoding`. Then you could choose `Simplified GBK` or `Simplified GB18030`, I think both should work.

**Comment by jerrychong25** [comment]
Hi @SheldonZhong,

Thanks for the help.

It is working now.
