### ISSUE TITLE
Syntax highlighting in code blocks of markdown

### ISSUE THREAD

**Issue by VariabileAleatoria** [Gimly/vscode-matlab#71]
When using code blocks in markdown, when you specify the language, the code gets syntax highlight

![md](https://user-images.githubusercontent.com/45683610/54077905-6c058a80-42bf-11e9-9142-808ef4ee3bde.png)

This is not happening with matlab and I read somewhere online that VSCode delegates the highlighting to the extension that have registered support of the language.
Is it possible to fix?

**Comment by Gimly** [comment]
With version 1.0 we've updated the syntax highlighting syntax which might have been the cause of the issue. Could you please tell me if you still experience the issue with that version?

**Comment by VariabileAleatoria** [comment]
unfortunately nothing changed to me

**Comment by Gimly** [comment]
Just to understand, you're adding markdown to a matlab source file?

**Comment by VariabileAleatoria** [comment]
> 
> 
> Just to understand, you're adding markdown to a matlab source file?

nope, i'm writing matlab in code blocks (triple backtics) of markdown documents

**Comment by Gimly** [comment]
So that would be an issue for the Markdown extension, not this one 😄. They could use the same grammar though.
