### ISSUE TITLE
Matlab extension unresponsive when I open this specific file.

### ISSUE THREAD

**Issue by haberdashPI** [Gimly/vscode-matlab#72]
All of a sudden (I'm not sure what of the things I changed matter) the vscode Matlab extension is becoming unresponsive.

It only seems to happen when I open [this file](https://github.com/haberdashPI/german_track/blob/0e98f4e17ad814bac5a3a6667409cf948275fad3/stimuli/src/create_mixtures.m). I'm guessing there is some issue with parsing the file??

This is an in-progress snapshot of a file I am revising (it will not run).

[Here is the profile report](https://drive.google.com/file/d/1Wjzdm1j6Pfiu7ouEBaj7_SbUcj47brTu/view?usp=sharing) that vscode generated.

Note that I cannot keep the repository containing the problematic file public indefinitely as it will eventually contain sensitive research data. Please let me know within the next week or two if you will need access to the file past March 28th 2019.

**Comment by haberdashPI** [comment]
A few more data points:

1. I tried a systematic search for the problem (i.e. delete half the code, see if it crashes VSCode, delete 3/4 of the code, etc...) but the source of the error was not a reliable location in the file, that i could tell. At some point while deleting lines from the file, the error stopped happening, but which set of lines I narrowed down to changed each time.

2. The [Octave](https://marketplace.visualstudio.com/items?itemName=toasty-technologies.octave) extension did not crash on this file.

3. The [newest version of the file](https://github.com/haberdashPI/german_track/blob/726f1ae0ebc3e615937de817cbe38824783249f3/stimuli/src/create_mixtures.m) does not seem to lead to the crash.

**Comment by Gimly** [comment]
Thanks for opening the issue and for the added information. I'll try to check what's going on. It might be a regex that works weirdly.

**Comment by Gimly** [comment]
With version 1.0 we've updated the syntax highlighting syntax which might have been the cause of the issue. Could you please tell me if you still experience the issue with that version?

**Comment by haberdashPI** [comment]
Yes: at least, when I open the offending content, the extension host no longer crashes. Seems to have fixed some other oddities I've noticed with syntax coloring in matlab.

Thank you!

**Comment by Gimly** [comment]
You're welcome, this is great news. I'm happy to have helped. Hope you like the extension. Cheers.
