### ISSUE TITLE
Add "Go to definition" for variable, class, function

### ISSUE THREAD

**Issue by wanzhiyu** [Gimly/vscode-matlab#75]
Thanks for this good extension!

Recently I've come to a situation that I need to deal with a lot of ".m" files with different classes and functions at the same time. Trouble is that I can't find my definition quickly. 
I also can't use auto-completion to get the class and function definitions in other files. 

Is it possible to implement these two features? Thanks a lot!

Picture below shows the "Go to definition" function in ".cs" files.
![Suggestion from CS](https://user-images.githubusercontent.com/18503895/55134837-ead64080-5164-11e9-982f-dbbd4fb781cc.jpg)

**Comment by jakelevi1996** [comment]
Thanks @Gimly for the good extension. I would also greatly appreciate the "Go to definition" feature.

**Comment by awesomeindustries** [comment]
I would also appreciate such a feature.

**Comment by Galileji** [comment]
Me too

**Comment by RobinTournemenne** [comment]
I submitted a pull request doing exaclty what you are all asking for! @Gimly may review it. 

In the mean time, if you want this functionnality, the hard way is to fork this project, do my modification (that you can find here: https://github.com/Gimly/vscode-matlab/pull/109),
publish it with the command: ```vsce package```, and replace the folder ```~/.vscode/extensions/gimly81.matlab-1.6.0/out```by the one created by the command ```vsce package```.

The easy way is to replace this folder by the one in the zip file I attach to this comment:

[out.zip](https://github.com/Gimly/vscode-matlab/files/4532672/out.zip)

**Comment by RobinTournemenne** [comment]
I am currently preparing a pull request for a better symbols detection within files and a reference finder throughout the project. In the mean time the native search function of vscode does the job if you tweak it enough.

**Comment by Gimly** [comment]
I'm sorry, I've been really busy recently and haven't had time to review your submission.

**Comment by Gimly** [comment]
Done thanks to awesome work by @RobinTournemenne available in version 2.0.0. Thanks again Robin!

**Comment by mpzanoosi** [comment]
Hey @Gimly  and @RobinTournemenne 
I am trying to use Go to definition ... but that's not working for me :/
for example I have `main.m` and `addsubdirs.m` files in one directory which in `main.m` I called the function `addsubdirs.m`; 
when I want to use "go to definition" it says: no definition found for 'addsubdirs'
I can use go to definition of matlab editor on these functions!

what is the problem?

**Comment by RobinTournemenne** [comment]
addsubdirs.m has to be in a folder of your VSCode project. Can you find the file addsubdirs.m in your VSCode explorer? If no then it is normal that you cannot find the definition. If yes, maybe the file is in an excluded folder regarding search (happens often for me but I do that on purpose).

If you are on the 2.2.0 version of the extension, I cannot say for sure that this feature still works.

**Comment by mpzanoosi** [comment]
@RobinTournemenne 
yup!

@Gimly 
this feature just works for 2.0.0 and 2.0.1 not furthermore!
2.2.0 has no "Go to definition" feature 
2.2.1 has it, but not working
seems something has been rollbacked!

@Gimly  thanks if you could merge and release a new version!

**Comment by mpzanoosi** [comment]
@RobinTournemenne 
however, does your feature work for functions in a `classdef`?
seems it does not work for them!
I can do with functions based on files....but not with functions in a class.

**Comment by RobinTournemenne** [comment]
I am not using classes in Matlab and scarcely know how they work. If you want to add a missing feature for the "goto definition", don't hesitate to propose a pull request, it is fairly easy to understand how it works looking at the corresponding commits:

https://github.com/Gimly/vscode-matlab/pull/109

**Comment by SNDST00M** [comment]
This has been addressed by the new Textmate LSP service!
