### ISSUE TITLE
colorization problem

### ISSUE THREAD

**Issue by BlueTeo91** [Gimly/vscode-matlab#76]
The colorization for all the matlab functions doesn't work.
Only for loop, switch and if (but the else is not colored for example) are recognized and properly colored, all others functions are not properly colored but left blank as thy're variables

**Comment by Gimly** [comment]
I'm sorry, I did switch the syntax grammar to an official syntax coming from Matworks, thinking it would fix all the issues I had since it was an official grammar. I didn't test it enough and I see that it brought a few new issues even though it did fix a few others.

**Comment by rlivings39** [comment]
One option, if the MathWorks repository doesn't want to support function highlighting is to factor out the function highlighting piece of the other grammar and use 2 grammars in VSCode. Since my PR triggered this change I'm happy to do that work.

@Gimly Let me know once you decide on staying with the MathWorks grammar or reverting. If you're staying with it I'll refactor to pull out the function highlighting.

**Comment by BlueTeo91** [comment]
> I'm sorry, I did switch the syntax grammar to an official syntax coming from Matworks, thinking it would fix all the issues I had since it was an official grammar. I didn't test it enough and I see that it brought a few new issues even though it did fix a few others.

Any updates about the issue? :)

**Comment by Gimly** [comment]
Not yet, a few issues were opened on @gauravsavadi's repository, but we didn't get any feedback yet. Let's say I'm giving it until Wednesday and I'll revert back to the grammar we had before.

@rlivings39 I'm honestly not sure what to do, on one hand I'd much rather have an official grammar "endorsed" by Mathworks, but on the other hand it has brought a lot of new issues and hasn't fixed a few other that I already had. What are the plans of Mathworks regarding this grammar? Do you plan on improving it with time and is it really something official that is going to be worked on?

**Comment by rlivings39** [comment]
@Gimly Apologies for the pain associated with my PR.

I've forwarded this discussion to the grammar's maintainer and asked them to comment here.

**Comment by gauravsavadi** [comment]
Hello @Gimly 
We are working on integrating the fixes to the above issues into the MathWorks repository. They should be integrated within a couple of days.

**Comment by gauravsavadi** [comment]
@Gimly 
MathWorks does indeed plan to support this grammar and improve it with time as new features get added to the language. 

With regards to your question about function highlighting i.e. this issue: https://github.com/gauravsavadi/MATLAB-Language-grammar/issues/3,

we do not plan to add highlighting to functions. Here is the rationale: https://github.com/github/linguist/issues/3904#issuecomment-347582820

However, @rlivings39 's proposed workaround should work for VSCode.

**Comment by gauravsavadi** [comment]
Thanks @rlivings39 for submitting the fix to the elseif issue. That fix has also been integrated into the MathWorks grammar, in addition to https://github.com/Gimly/vscode-matlab/issues/77

**Comment by rlivings39** [comment]
https://github.com/rlivings39/vscode-matlab/commit/040d26385b4707b849b92c69f7a13f859188d4ca is a first attempt at the workaround that @gauravsavadi mentioned. 

It factors out the function highlighting piece of the original vscode-matlab grammar, adds that to vscode-matlab, and combines it with the MathWorks language grammar as an [injection grammar](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) to combine it.

**Comment by Gimly** [comment]
@rlivings39 What about @zhaouv's PR (https://github.com/mathworks/MATLAB-Language-grammar/pull/3), do you plan on merging it? Is there something needed to fix before merging it?

**Comment by Gimly** [comment]
Version 1.1.0 should fix the issue with if/elseif and the functions issue. Feel free to reopen the issue (or open another one) if you feel it hasn't been completely fixed.

**Comment by rlivings39** [comment]
I'll leave that up to @gauravsavadi as he's the maintainer for the grammar. Glancing over the diff from the PR it looks like many of the issues it attempts to address have independently been fixed.

**Comment by gauravsavadi** [comment]
As @rlivings39 mentioned, the issues have been fixed in the latest MathWorks grammar, so I think we should be all set.
