### ISSUE TITLE
Highliting issue

### ISSUE THREAD

**Issue by Sanmingzh1** [Gimly/vscode-matlab#78]
￼
<img width="550" alt="screenshot" src="https://user-images.githubusercontent.com/42461811/55401197-9a0a8180-5582-11e9-999d-b716ccf3e44b.png">
It can't show highlighting for function name or variables.

**Comment by Gimly** [comment]
Good news, thanks to @rlivings39's work, this issue should be fixed in version 1.1.0. Don't hesitate to reopen if you feel there still is an issue.
