### ISSUE TITLE
File association language case doesn't match displayed language name

### ISSUE THREAD

**Issue by tintod** [Gimly/vscode-matlab#8]
![image](https://cloud.githubusercontent.com/assets/20996008/17631700/26389a9e-6093-11e6-86d9-392afa649ba1.png)

Overriding default file-language associations (objective-C) is case sensitive, and doesn't match the displayed language name.  i.e. matlab vs. MATLAB.
This might be easily resolved by putting a short note in the readme about the proper way to change file associations.

I'm running stable v1.4.0 and was able to repeat the issue by changing the string from matlab back to MATLAB.

**Comment by Gimly** [comment]
Thanks for the info, I'll definitely update the Readme with this.

**Comment by tintod** [comment]
Thanks Xavier, I can see the addition after updating the extension.
![image](https://cloud.githubusercontent.com/assets/20996008/17736208/7c369012-6454-11e6-8e54-2929358da764.png)

**Comment by Gimly** [comment]
Thanks for the help, it was a very useful feedback.
