### ISSUE TITLE
Git Integration Fails When Matlab Files are Open

### ISSUE THREAD

**Issue by singofwalls** [Gimly/vscode-matlab#81]
With the Matlab extension enabled and a Matlab file open in an editor when VSCode is loaded, Git integration never loads (the version control tab never finds a repo and manually opening a repo does nothing). Various extensions (Such as TodoTree and GitLens) also fail to load. Disabling the Matlab extension and reloading fixes the problem. However, re-enabling the extension causes the git integration to stop working again. Reloading VSCode with Matlab enabled while no files are open in the editor allows git integration to load for the project (i.e. the git repo is displayed in the version control tab). However, subsequently opened files do not display changes as they normally do.  
  
**Details**:
Windows 7  
Rather large Matlab project (~58 MB). Opening smaller sub-folders does not fix the problem, however.  

I have tried numerous versions of the extension but the problem remained with each. 
Let me know if there's any more info I can provide to hopefully resolve this.

Great extension anyhow :)

**Comment by yihengli** [comment]
I have exactly the same issue. When matlab plugin is enabled, several of my extensions will fail to be fully functional and git integration will not work. I also noticed very high CPU usage (almost 100%) of code helper at background caused by this plugin.

As I don't have a matlab client locally and simply want to use this plugin to do syntax highlighting. I was wondering if that's because it kept looking for the client at the background. (I might be wrong)

I am with a MBP15, Mid2015.

**Comment by yihengli** [comment]
As I play around for a while, it seems more like a VSCode issue for me. When I switch to Version 1.35.0-insider (1.35.0-insider), the plugin starts to work fine and git integration is back.

**Comment by Jamen1993** [comment]
I have the same problem. The matlab extension somehow keeps VSC from working correctly after opening an associated file. Deactivating the Matlab extension makes it work correctly again.

**Comment by rlivings39** [comment]
@yihengli @Jamen1993 is this still reproducible with vscode 1.35? I've tried on several large projects and can't reproduce such issues.

**Comment by Jamen1993** [comment]
I currently have version 1.35.1 installed.

I have a particular Matlab file that regularly causes problems, like
keeping other extensions from working probably and also killing the Git
integration.

Is there any log file that would be of help?

Am Mo., 24. Juni 2019 um 12:39 Uhr schrieb Ryan Livingston <
notifications@github.com>:

**Comment by rlivings39** [comment]
Are you able to share the MATLAB file that causes problems? Is that file also tracked in Git?

I'll need to think about what kind of logs may be helpful as I'm pretty new to the vscode extension development workflows. @Gimly any thoughts about what logs we could collect to debug this?

**Comment by Jamen1993** [comment]
Shure, here is the respective file and yes, the file is tracked.

The problems start as soon as I open the file, no editing is required.

[lin_kk_test.zip](https://github.com/Gimly/vscode-matlab/files/3320880/lin_kk_test.zip)

**Comment by rlivings39** [comment]
Thanks will take a look. I can reproduce significant slowness with the file you shared so thanks!

**Comment by rlivings39** [comment]
Quick profiling shows that all of the time is spent in [documentSymbolProvider.ts](https://github.com/Gimly/vscode-matlab/blob/master/src/documentSymbolProvider.ts) in the call to `test` matching the regular expression. I won't get a chance to take a further look until later.

**Comment by Jamen1993** [comment]
I could also provide proper input data for the function if this would be of
help.

**Comment by rlivings39** [comment]
It seems to simply be the extension trying to parse the code to find symbols (i.e. function definitions) that is slow. Those symbols are shown in the breadcrumbs in VSCode and in the outline view (`Ctrl+Shift+P Focus on outline view`). So there's no need to run the code or have runtime inputs. But thanks!

**Comment by Jamen1993** [comment]
Parsing seems to be the the correct direction.

Outline view and breadcrumbs fail alongside with the source control
provider and the other stuff.
