### ISSUE TITLE
High CPU usage with GitLens

### ISSUE THREAD

**Issue by yihengli** [Gimly/vscode-matlab#82]
## Issue

When I run `matlab` extension with `GitLens`, I noticed the CPU could run up to 100% and Git related features in VSCode are broken. (cannot be opened)

## Reproduce

1. Clean VSCode with only matlab and gitlens installed
2. Open an edited matlab file
3. Reload window

## Env
Vscode: Version 1.35.0-insider (1.35.0-insider)
Matlab: 1.1.0
Gitlens: 9.8.1

## Others

1. I don't have matlab client installed, thus there will be error `mlint not found` etc. Not sure if it's relevant
2. Tested without Gitlens, works well with some other extensions
3. I have also attached the cpuprofile, hope it helps.
4. Not sure if I should post this on GItlens, but I observed the usage is mainly from Matlab.
5. may be relevant to #81 

Also attached `cpuprofile` for reference.

[yli_matlab.cpuprofile.txt](https://github.com/Gimly/vscode-matlab/files/3217707/yli_matlab.cpuprofile.txt)

**Comment by rlivings39** [comment]
I poked at this a bit and saw that with GitLens enabled and the outline view open the symbol provider code is called 2-3 times per edit I make to the file. With GitLens disabled the symbol provider code is only called once per edit. Somehow it looks like the code lens info added to the document trigger additional parses. Not sure what a fix would be.

**Comment by Gimly** [comment]
The fix implemented by @rlivings39 has been published in the extension v1.2.0. Could you please check if the issues is still there?

**Comment by Gimly** [comment]
As far as I can tell, this was fixed by version 1.2.0. I'm closing the issue now, feel free to reopen or create another if you feel this is not the case.
