### ISSUE TITLE
Class properties highlighting/colourisation issue

### ISSUE THREAD

**Issue by BirukTes** [Gimly/vscode-matlab#89]
I suppose the properties of a class were to look like the Matlab editor's contrast between which is the variable and the type. Please the image.
![image](https://user-images.githubusercontent.com/23151263/63949698-b26bc300-ca72-11e9-91ee-941a81226a48.png)

**Comment by rlivings39** [comment]
This looks to be partially theme-dependent. I see the behavior you've shown with the `Light (Visual Studio)` theme. However the `Light+ (default theme)` shows a difference
![vscodePropHighlight](https://user-images.githubusercontent.com/43882944/64015422-84c65e80-caf2-11e9-943b-cc45c4e76fe0.png)

There may be something in the grammar that can be improved. Will take a look.

**Comment by rlivings39** [comment]
Created https://github.com/mathworks/MATLAB-Language-grammar/issues/8 to add this to the grammar

**Comment by rlivings39** [comment]
@BirukTes Let me know if you've got any thoughts about the proposed highlighting at:

https://github.com/mathworks/MATLAB-Language-grammar/pull/9

**Comment by BirukTes** [comment]
@relivings39 Sure, thank you. Changing the theme made a difference.

**Comment by Gimly** [comment]
Thanks for the fix @rlivings39 I'll update the grammar when your PR has been merged

**Comment by rlivings39** [comment]
@Gimly the PR is merged. Do you want to update the grammar or should I send a PR?

**Comment by Gimly** [comment]
I'll do the update and push a new version, thanks!

**Comment by Gimly** [comment]
New version 1.3.0 with the new grammar from @rlivings39 has been uploaded to the VSCode marketplace. The issue should be fixed by it. Thanks again @rlivings39!
