### ISSUE TITLE
Syntax Highlighting of if-elseif-else

### ISSUE THREAD

**Issue by kugelrund** [Gimly/vscode-matlab#9]
Hey, thx for the matlab support in vscode!

I got some weird issues with simple syntax highlighting of if-elseif-else statements, see image.
![test](https://cloud.githubusercontent.com/assets/6236137/17754784/81a1885e-64d6-11e6-8ad2-029d36c593a0.png)
 I'm not using mlint, is that an issue?

**Comment by Gimly** [comment]
Hi,

Thanks for reporting this, definitely not an issue caused by not using mlint, the coloration and linting are two very different things.

Those syntax coloration issues are really weird, I'll have to look it up.

**Comment by jankap** [comment]
Any updates on this? I'm having the same problems. First I thought it would be an issue of missing parentheses after the if or elseif statement, but that seems not to be the case.

**Comment by Gimly** [comment]
Sorry,  I haven't had time to fix it. But I'd be happy to have help on that if you're interested.

**Comment by kintaat** [comment]
I think it is caused by some syntax rules of 'if'
![screenshot from 2017-02-17 16-12-08](https://cloud.githubusercontent.com/assets/6628575/23057648/0d5d1de6-f52c-11e6-877e-3a40e8b3be62.png)

**Comment by jankap** [comment]
I'd like to help but my Typescript knowledge is very limited. Do you have a starting point?

**Comment by amauragis** [comment]
Someone who knows what they are talking about should validate this, but I looked at if section of the converted textmate bundle from the Atom matlab language [here](https://github.com/JamesRitchie/language-matlab/blob/master/grammars/m.cson).

The difference I noticed was the use of a 'captures' key vs a 'beginCaptures' key.  I have absolutely no idea what this means, so I swapped it blindly.

I just changed line 242 and 273 `beginCaptures` to `captures`.
![code_2017-02-27_15-46-03](https://cloud.githubusercontent.com/assets/2589199/23379157/dd32cf82-fd03-11e6-8cf8-108bb2ecf2c5.png)

 Seems to work.  Thoughts?

**Comment by haberdashPI** [comment]
Highlighting `else` seems to be a problem again:

![image](https://user-images.githubusercontent.com/7861592/55725805-685b4580-59dc-11e9-8703-23e595a697c3.png)

This image also reveals some other odd syntax issues I'm not sure how to describe (the pruple 'e' and '1' in `use_eeg1`

**Comment by tgaochn** [comment]
The same issue for me.
![Clipboard_20190409](https://user-images.githubusercontent.com/22850831/55840953-eb6ebf80-5af2-11e9-88e0-34975051ca24.png)

@Gimly It seems that this issue can be solved by update Matlab.tmLanguage file.
"else" is highlighted after I replace the file with this one:
https://github.com/chrismccord/sublime-files/blob/master/Packages/Matlab/Matlab.tmLanguage
Will you consider update the file in the next version?

![Clipboard_20190409 (2)](https://user-images.githubusercontent.com/22850831/55841074-5ddf9f80-5af3-11e9-9929-04519786cfda.png)

**Comment by tgaochn** [comment]
> Highlighting `else` seems to be a problem again:
> 
> ![image](https://user-images.githubusercontent.com/7861592/55725805-685b4580-59dc-11e9-8703-23e595a697c3.png)
> 
> This image also reveals some other odd syntax issues I'm not sure how to describe (the pruple 'e' and '1' in `use_eeg1`

Consider updating Matlab.tmLanguage file. See my comment.
