### ISSUE TITLE
Support for function argument validation

### ISSUE THREAD

**Issue by skycaptain** [Gimly/vscode-matlab#90]
Matlab 2019b introduced [function argument validation](https://www.mathworks.com/help/matlab/ref/arguments.html). Currently syntax highlighting and proper indentation does not work for an `arguments` block.

**Comment by rlivings39** [comment]
Created https://github.com/mathworks/MATLAB-Language-grammar/issues/13 to add syntax highlighting for the `arguments` block. Can add indentation directly here.

**Comment by rlivings39** [comment]
@Gimly we merged the PR to support function argument validation in highlighting in the MathWorks grammar. When the upstream grammar is updated how do you want us to coordinate an update in vscode-matlab? I can send a PR, or ping you, or something else as you prefer.

**Comment by Gimly** [comment]
@rlivings39 either open a PR directly or ping me, for example by opening an issue here, whatever is the simplest for you.
