### ISSUE TITLE
wrong linting when whitespace between two strings

### ISSUE THREAD

**Issue by ocehugo** [Gimly/vscode-matlab#92]
The code is currently linting whitespace between strings inside brackets. It should not change the whitespace if entries are not separated by comma, otherwise the linting change the evaluation:

```
abc = ['a' 'b' 'c']; % abc='abc'
```

After linting
```
abc = ['a''b''c']; % abc='a'b'c'
```

I got some broken files since the strings do not match anymore with the previous expectation.

**Comment by ocehugo** [comment]
a comma should be the correct substitute

**Comment by rlivings39** [comment]
Can you elaborate on what actions we'd take to reproduce this? I just tried putting the code:
```matlab
abc = ['a' 'b' 'c']; % abc='abc'
```
into a MATLAB file and saving the file. No whitespace was removed for me.

**Comment by ocehugo** [comment]
@rlivings39, I just realize this is the wrong repo, my issue is with https://github.com/affenwiesel/matlab-formatter-vscode, not this one

sorry about the mistake.

**Comment by rlivings39** [comment]
No worries and thanks for taking the time to report issues either way
