### ISSUE TITLE
messy Chinese code on error hints

### ISSUE THREAD

**Issue by m13953842591** [Gimly/vscode-matlab#96]
![image](https://user-images.githubusercontent.com/30395886/67750322-f3c82100-fa69-11e9-93cf-7e35cc3fa1f7.png)

I am a Chinese coder and I encountered this issue. I have changed the language of MATLAB to English, and I also tried to change the font of MATLAB and VScode.  They all didn't work.

**Comment by Bergja** [comment]
Change your Linter Encoding in vscode setting to gbk
the error hints will display correctly
