### ISSUE TITLE
End of Line comments not recognized

### ISSUE THREAD

**Issue by apassy** [Gimly/vscode-matlab#97]
Let me preface this by saying that I'm not sureif this is my problem, or a problem with the extension.  My vs code install is relatively new.

note line 14, e.g.
![image](https://user-images.githubusercontent.com/16908477/67953479-38180600-fbbd-11e9-9d74-7b396fb2f287.png)

**Comment by apassy** [comment]
here is the code:
classdef FtsConfigData
% 
% This class manages some common operations on the config data, but is a thin wrapper around Table.  users are expected to eventually grab the tbl property and make use of that data.

properties (SetAccess = protected)
    tbl@table scalar;
    origTbl@table scalar;
    parsed@logical scalar = false;
    colsPerFactor@uint32 scalar;
    maxCols@uint32 scalar = 20;
    numFactors@uint32 scalar;
    factorStart@uint32 scalar;
    S@cell vector; %output symbols
    D@cell matrix; %basically all graph points - twocols, output symbol, and input symbol 
    nodenames@cell vector; %unique symbols in table
    E@cell vector; %input symbols in table (i.e. referred to but not found in the FTS_Symbol column)
    G@digraph scalar; %graph
    allRegionInfo@cell;
    factorRoot@string vector;
    symbolColOffsets@double vector;
    verNum@uint32 scalar;
    mostRecent@logical scalar = false;
    
end%public props
end % class def

**Comment by rlivings39** [comment]
It's an issue introduced by my changes to improve argument and property validation highlighting. I opened a parallel issue in the MATLAB TextMate grammar repo https://github.com/mathworks/MATLAB-Language-grammar/issues/16
