### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by SimonMossmyr** [Gimly/vscode-matlab#98]
Text following triple-dot is sometimes not correctly highlighted:

![Screenshot from 2019-11-06 16-33-25](https://user-images.githubusercontent.com/19503193/68312524-77f65600-00b3-11ea-8026-b140dbf3a596.png)

**Comment by rlivings39** [comment]
Created https://github.com/mathworks/MATLAB-Language-grammar/issues/18 against the MATLAB TextMate grammar being used in vscode.

**Comment by SimonMossmyr** [comment]
I did some experimenting, and there's more to this:

![Screenshot from 2019-11-06 16-48-35](https://user-images.githubusercontent.com/19503193/68313744-5eeea480-00b5-11ea-89cf-953a1ad42d42.png)

**Comment by SimonMossmyr** [comment]
@rlivings39 Ah didn't know you used a library for highlighting. Thanks for opening the issue for me.

**Comment by rlivings39** [comment]
Can you please cross-post your additional investigation to the other issue so your test cases can be considered when fixing it?
